# Generated by Django 5.0 on 2023-12-20 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('totalRating', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('inventory', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.TextField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf_token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Placed')),
                ('total_items', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('streetAddress', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.TextField(blank=True, max_length=2, null=True)),
                ('ship_zip', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('bil_zip', models.CharField(blank=True, max_length=5, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf_token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sub_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
    ]
