# Generated by Django 5.0 on 2023-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_customer_products_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
