# Generated by Django 5.0 on 2023-12-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_streetaddress_order_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
