# Generated by Django 5.0 on 2023-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_with_shipping',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
