# Generated by Django 5.0 on 2023-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_csrf_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_token',
            field=models.CharField(default=0, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
