# Generated by Django 5.0 on 2023-12-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_product_remove_finch_toys_remove_finch_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='numOfItems',
            new_name='totalItems',
        ),
    ]
