# Generated by Django 5.0 on 2023-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_numofitems_order_totalitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='totalRating',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
