# Generated by Django 5.0 on 2023-12-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_product_created_at_product_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_token',
            new_name='session_id',
        ),
    ]
