# Generated by Django 5.0 on 2023-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
