# Generated by Django 5.0 on 2023-12-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_orderitem_subtotal_alter_orderitem_csrf_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_item_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
